# Generated by Django 4.1.2 on 2022-10-31 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='OTM')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(choices=[('JISMONIY', 'Jismoniy shaxs'), ('YURIDIK', 'Yuridik shaxs')], default='JISMONIY', max_length=20)),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.SH.')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tashkinot nomi')),
                ('payment_amount', models.IntegerField(verbose_name='Homiylik Summasi')),
                ('allocated_amount', models.IntegerField(default=0, verbose_name='Sarflagan pullari')),
                ('add_day', models.DateField(auto_now_add=True, verbose_name='Sana')),
                ('update_day', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('YANGI', 'Yangi'), ('MODERATSIYADA', 'Moderatsiyada'), ('TASDIQLANGAN', 'Tasdiqlangan'), ('BEKOR QILINGAN', 'Bekor qilingan')], default='YANGI', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.SH.')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam')),
                ('student_type', models.CharField(choices=[('MAGISTR', 'Magistr'), ('BAKALAVR', 'Bakalavr')], default='BAKALAVR', max_length=20)),
                ('allocated_amount', models.IntegerField(default=0)),
                ('contract_amount', models.IntegerField(verbose_name='Kontrakt miqdori')),
                ('add_day', models.DateField(auto_now_add=True, verbose_name='SANA')),
                ('update_day', models.DateTimeField(auto_now=True)),
                ('otm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metsenat.otm')),
            ],
        ),
        migrations.CreateModel(
            name='Metsenat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField(verbose_name='Ajratilgan summa')),
                ('payment_day', models.DateField(auto_now_add=True)),
                ('update_day', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metsenat.sponsor')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metsenat.student')),
            ],
        ),
    ]
